### ISSUE TITLE
PancakeSwap LP Rewards, broken URL

### ISSUE THREAD

**Issue by triloger** [oikos-cash/minter#6]
Inside LP Rewards Tab, on the PancakeSwap V2 (BNB/OUSD) LP Token Rewards the hyperlink for the LP to add liquidity on PCS is broken and should be updated to **https://pancakeswap.finance/add/BNB/0x6BF2Be9468314281cD28A94c35f967caFd388325**
![image](https://user-images.githubusercontent.com/38734531/148655296-95f1a5aa-0c4d-47c6-853f-9161f0da1834.png)
![image](https://user-images.githubusercontent.com/38734531/148655155-561521fe-6640-4827-96f5-6c6be555091d.png)

**Comment by oikos1** [comment]
Handled with [f814d78](https://github.com/oikos-cash/minter/commit/f814d7822b1806184d63e8ae5caec12b6109e728) and [66f854d](https://github.com/oikos-cash/minter/commit/66f854d521f7153ddb3c8e2b93c7cb05a87aa4e4)
